SELECT COUNTRY,COALESCE(T1+T2,0) AS TOTALMATCH,COALESCE(TOTALGOAL,0) AS TOTALGOAL
FROM TEAM
         LEFT OUTER JOIN (SELECT FORTEAM,COUNT(*) AS TOTALGOAL
                          FROM GOALINFO
                          WHERE PENALTY = false
                          GROUP BY FORTEAM) AS GOAL ON GOAL.FORTEAM = TEAM.COUNTRY,
     (SELECT TEAM1,COUNT(*) AS T1
      FROM MATCH
      GROUP BY TEAM1),
     (SELECT TEAM2,COUNT(*) AS T2
      FROM MATCH
      GROUP BY TEAM2)
WHERE TEAM1 = TEAM.COUNTRY AND TEAM2 = TEAM.COUNTRY;

