-- the player summary: name, total goal, yellow card, red card
SELECT FNAME,LNAME,PERSON.PID,COALESCE(TOTALGOAL,0) AS TOTALGOAL,COALESCE(TOTALYELLOWCARD,0) AS TOTALYELLOWCARD,COALESCE(TOTALREDCARD,0) AS TOTALREDCARD
FROM PERSON
         LEFT OUTER JOIN (SELECT PID,SUM(Y1 + Y2) AS TOTALYELLOWCARD,SUM(R) AS TOTALREDCARD
                          FROM PLAYERGAMEINFO
                          GROUP BY PID) AS CARD ON CARD.PID = PERSON.PID
         LEFT OUTER JOIN (SELECT GOALINFO.PLAYER, COUNT(*) AS TOTALGOAL
                          FROM GOALINFO
                          GROUP BY GOALINFO.PLAYER) AS GOAL ON PLAYER = PERSON.PID
ORDER BY TOTALGOAL DESC;